version: "3.7"
services:

## --------------------------- NEXCONSULT API --------------------------- ##

  nexconsult-api:
    image: felipyfgs17/nexconsult-api:latest ## Imagem da aplicação NexConsult

    volumes:
      - nexconsult_logs:/app/logs

    networks:
      - Gacont ## Nome da rede interna

    environment:
      ## Configurações da aplicação
      - PORT=3000
      - HEADLESS=true
      - DEBUG_MODE=false
      - SOLVE_CAPTCHA_API_KEY=bd238cb2bace2dd234e32a8df23486f1 ## Chave da API SolveCaptcha

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.nexconsult_api.rule=Host(`nexconsult.gacont.com.br`) ## URL da API
        - traefik.http.routers.nexconsult_api.entrypoints=websecure
        - traefik.http.routers.nexconsult_api.tls.certresolver=letsencryptresolver
        - traefik.http.services.nexconsult_api.loadbalancer.server.port=3000
        - traefik.http.services.nexconsult_api.loadbalancer.passHostHeader=true
        - traefik.http.routers.nexconsult_api.service=nexconsult_api

## --------------------------- NEXCONSULT API --------------------------- ##

volumes:
  nexconsult_logs:
    external: true
    name: nexconsult_logs

networks:
  Gacont: ## Nome da rede interna
    external: true
    name: Gacont ## Nome da rede interna
