version: '3.8'

services:
  nexconsult-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HEADLESS=true
      - DEBUG_MODE=false
      - CAPTCHA_API_KEY=${CAPTCHA_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
