version: "3.7"
services:

## --------------------------- PORTAINER --------------------------- ##

  portainer:
    image: portainer/portainer-ce:latest ## Versão do Portainer
    command: -H unix:///var/run/docker.sock

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer_data:/data"

    networks:
      - Gacont ## Nome da rede interna

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.gacont.com.br`) ## URL do Portainer
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls.certresolver=letsencryptresolver
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.services.portainer.loadbalancer.passHostHeader=true
        - traefik.http.routers.portainer.service=portainer

## --------------------------- PORTAINER --------------------------- ##

volumes:
  portainer_data:
    external: true
    name: portainer_data

networks:
  Gacont: ## Nome da rede interna
    external: true
    name: Gacont ## Nome da rede interna
