// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.nexconsult.com/support",
            "email": "support@nexconsult.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/browser/health": {
            "get": {
                "description": "Get the health status of the browser pool",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Browser"
                ],
                "summary": "Get browser pool health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/browser/restart": {
            "post": {
                "description": "Restart all browsers in the pool",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Browser"
                ],
                "summary": "Restart browser pool",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/browser/stats": {
            "get": {
                "description": "Get detailed browser pool statistics and metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Browser"
                ],
                "summary": "Get browser pool statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/clear": {
            "delete": {
                "description": "Clear all cached CNPJ data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Clear all cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/stats": {
            "get": {
                "description": "Get detailed cache statistics and metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Get cache statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cache/{cnpj}": {
            "delete": {
                "description": "Delete a specific CNPJ entry from cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cache"
                ],
                "summary": "Delete specific CNPJ from cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CNPJ number to delete from cache",
                        "name": "cnpj",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cnpj/batch": {
            "post": {
                "description": "Retrieve detailed information about multiple CNPJs from Receita Federal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CNPJ"
                ],
                "summary": "Get multiple CNPJ information",
                "parameters": [
                    {
                        "description": "Batch CNPJ request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.BatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.BatchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cnpj/{cnpj}": {
            "get": {
                "description": "Retrieve detailed information about a CNPJ from Receita Federal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CNPJ"
                ],
                "summary": "Get CNPJ information",
                "parameters": [
                    {
                        "type": "string",
                        "example": "11222333000181",
                        "description": "CNPJ number (14 digits)",
                        "name": "cnpj",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.CNPJResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get the health status of the API and its dependencies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Check if the API is alive and responding",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Check if the API is ready to serve requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Get detailed application metrics and statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get application metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.MetricsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_nexconsult_cnpj-api_internal_models.BatchRequest": {
            "type": "object",
            "required": [
                "cnpjs"
            ],
            "properties": {
                "cnpjs": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"11222333000181\"",
                        "\"11333444000172\"]"
                    ]
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.BatchResponse": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "type": "integer",
                    "example": 5200
                },
                "errors": {
                    "type": "integer",
                    "example": 0
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.BatchResult"
                    }
                },
                "success": {
                    "type": "integer",
                    "example": 2
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "total": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.BatchResult": {
            "type": "object",
            "properties": {
                "cnpj": {
                    "type": "string",
                    "example": "11222333000181"
                },
                "data": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.CNPJResponse"
                },
                "duration_ms": {
                    "type": "integer",
                    "example": 2500
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.BrowserMetrics": {
            "type": "object",
            "properties": {
                "active_browsers": {
                    "type": "integer",
                    "example": 8
                },
                "queue_size": {
                    "type": "integer",
                    "example": 3
                },
                "total_browsers": {
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.CNAEInfo": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string",
                    "example": "6201-5/00"
                },
                "descricao": {
                    "type": "string",
                    "example": "Desenvolvimento de programas de computador sob encomenda"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.CNPJResponse": {
            "type": "object",
            "properties": {
                "cache": {
                    "type": "boolean",
                    "example": false
                },
                "capital_social": {
                    "type": "string",
                    "example": "1000000,00"
                },
                "cnae_principal": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.CNAEInfo"
                },
                "cnae_secundarias": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.CNAEInfo"
                    }
                },
                "cnpj": {
                    "type": "string",
                    "example": "11.222.333/0001-81"
                },
                "consultado_em": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "data_inicio_atividade": {
                    "type": "string",
                    "example": "03/11/2005"
                },
                "data_situacao": {
                    "type": "string",
                    "example": "03/11/2005"
                },
                "data_situacao_especial": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endereco": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.EnderecoInfo"
                },
                "ente_federativo_responsavel": {
                    "type": "string"
                },
                "motivo_situacao": {
                    "type": "string",
                    "example": "SEM MOTIVO"
                },
                "natureza_juridica": {
                    "type": "string",
                    "example": "206-2 - SOCIEDADE EMPRESÁRIA LIMITADA"
                },
                "nome_fantasia": {
                    "type": "string",
                    "example": "Empresa Exemplo"
                },
                "porte": {
                    "type": "string",
                    "example": "DEMAIS"
                },
                "qualificacao_responsavel": {
                    "type": "string"
                },
                "razao_social": {
                    "type": "string",
                    "example": "EMPRESA EXEMPLO LTDA"
                },
                "situacao": {
                    "type": "string",
                    "example": "ATIVA"
                },
                "situacao_especial": {
                    "type": "string"
                },
                "socios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.SocioInfo"
                    }
                },
                "telefones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tempo_consulta_ms": {
                    "type": "integer",
                    "example": 2500
                },
                "tipo_empresa": {
                    "type": "string",
                    "example": "MATRIZ"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.CacheMetrics": {
            "type": "object",
            "properties": {
                "hit_rate": {
                    "type": "number",
                    "example": 85.5
                },
                "hits": {
                    "type": "integer",
                    "example": 1240
                },
                "misses": {
                    "type": "integer",
                    "example": 210
                },
                "size": {
                    "type": "integer",
                    "example": 15000
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.EnderecoInfo": {
            "type": "object",
            "properties": {
                "bairro": {
                    "type": "string",
                    "example": "CENTRO"
                },
                "cep": {
                    "type": "string",
                    "example": "01234-567"
                },
                "complemento": {
                    "type": "string",
                    "example": "SALA 456"
                },
                "logradouro": {
                    "type": "string",
                    "example": "RUA EXEMPLO"
                },
                "municipio": {
                    "type": "string",
                    "example": "SÃO PAULO"
                },
                "numero": {
                    "type": "string",
                    "example": "123"
                },
                "uf": {
                    "type": "string",
                    "example": "SP"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_CNPJ"
                },
                "error": {
                    "type": "string",
                    "example": "Invalid CNPJ format"
                },
                "message": {
                    "type": "string",
                    "example": "CNPJ must contain exactly 14 digits"
                },
                "path": {
                    "type": "string",
                    "example": "/api/v1/cnpj/11222333000181"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.HealthResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.ServiceInfo"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m45s"
                },
                "version": {
                    "type": "string",
                    "example": "2.0.0"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.MetricsResponse": {
            "type": "object",
            "properties": {
                "browser": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.BrowserMetrics"
                },
                "cache": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.CacheMetrics"
                },
                "performance": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.PerformanceMetrics"
                },
                "requests": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.RequestsMetrics"
                },
                "system": {
                    "$ref": "#/definitions/github_com_nexconsult_cnpj-api_internal_models.SystemMetrics"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.PerformanceMetrics": {
            "type": "object",
            "properties": {
                "avg_response_time_ms": {
                    "type": "integer",
                    "example": 2500
                },
                "p95_response_time_ms": {
                    "type": "integer",
                    "example": 5200
                },
                "p99_response_time_ms": {
                    "type": "integer",
                    "example": 8100
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.RequestsMetrics": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "integer",
                    "example": 50
                },
                "success": {
                    "type": "integer",
                    "example": 1450
                },
                "success_rate": {
                    "type": "number",
                    "example": 96.67
                },
                "total": {
                    "type": "integer",
                    "example": 1500
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.ServiceInfo": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "last_check": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "response_time_ms": {
                    "type": "integer",
                    "example": 150
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.SocioInfo": {
            "type": "object",
            "properties": {
                "cpf_cnpj_socio": {
                    "type": "string",
                    "example": "***123456**"
                },
                "data_entrada_sociedade": {
                    "type": "string",
                    "example": "03/11/2005"
                },
                "nome": {
                    "type": "string",
                    "example": "JOÃO DA SILVA"
                },
                "pais_origem": {
                    "type": "string",
                    "example": "BRASIL"
                },
                "qualificacao_representante": {
                    "type": "string"
                },
                "qualificacao_socio": {
                    "type": "string",
                    "example": "49-SÓCIO-ADMINISTRADOR"
                },
                "representante_legal": {
                    "type": "string"
                }
            }
        },
        "github_com_nexconsult_cnpj-api_internal_models.SystemMetrics": {
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "type": "number",
                    "example": 45.2
                },
                "goroutines": {
                    "type": "integer",
                    "example": 125
                },
                "memory_usage": {
                    "type": "number",
                    "example": 512.5
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "CNPJ Consultation API",
	Description:      "High-performance CNPJ consultation API built with Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
