// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@cnpjconsultor.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cnpj/{cnpj}": {
            "get": {
                "description": "Consulta dados de um CNPJ na Receita Federal com resolução automática de captcha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CNPJ"
                ],
                "summary": "Consulta dados de um CNPJ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CNPJ (com ou sem formatação)",
                        "name": "cnpj",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Usar cache (sempre false - busca direta)",
                        "name": "cache",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.CNPJData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica se o sistema está funcionando",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistema"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Retorna estatísticas e status do sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sistema"
                ],
                "summary": "Status do sistema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WorkerStats"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Atividade": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                }
            }
        },
        "types.AtividadesInfo": {
            "type": "object",
            "properties": {
                "principal": {
                    "$ref": "#/definitions/types.Atividade"
                },
                "secundarias": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Atividade"
                    }
                }
            }
        },
        "types.CNPJData": {
            "type": "object",
            "properties": {
                "atividades": {
                    "$ref": "#/definitions/types.AtividadesInfo"
                },
                "cnpj": {
                    "$ref": "#/definitions/types.CNPJInfo"
                },
                "comprovante": {
                    "$ref": "#/definitions/types.ComprovanteInfo"
                },
                "contato": {
                    "$ref": "#/definitions/types.ContatoInfo"
                },
                "empresa": {
                    "$ref": "#/definitions/types.EmpresaInfo"
                },
                "endereco": {
                    "$ref": "#/definitions/types.EnderecoInfo"
                },
                "metadados": {
                    "$ref": "#/definitions/types.MetadadosInfo"
                },
                "situacao": {
                    "$ref": "#/definitions/types.SituacaoInfo"
                }
            }
        },
        "types.CNPJInfo": {
            "type": "object",
            "properties": {
                "data_abertura": {
                    "type": "string"
                },
                "numero": {
                    "type": "string"
                },
                "tipo": {
                    "description": "MATRIZ ou FILIAL",
                    "type": "string"
                }
            }
        },
        "types.CacheInfo": {
            "type": "object",
            "properties": {
                "hit_rate": {
                    "type": "number"
                },
                "hits": {
                    "type": "integer"
                },
                "misses": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "types.ComprovanteInfo": {
            "type": "object",
            "properties": {
                "data_emissao": {
                    "type": "string"
                },
                "hora_emissao": {
                    "type": "string"
                }
            }
        },
        "types.ContatoInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                }
            }
        },
        "types.EmpresaInfo": {
            "type": "object",
            "properties": {
                "natureza_juridica": {
                    "$ref": "#/definitions/types.NaturezaJuridica"
                },
                "nome_fantasia": {
                    "type": "string"
                },
                "porte": {
                    "type": "string"
                },
                "razao_social": {
                    "type": "string"
                }
            }
        },
        "types.EnderecoInfo": {
            "type": "object",
            "properties": {
                "bairro": {
                    "type": "string"
                },
                "cep": {
                    "type": "string"
                },
                "complemento": {
                    "type": "string"
                },
                "logradouro": {
                    "type": "string"
                },
                "municipio": {
                    "type": "string"
                },
                "numero": {
                    "type": "string"
                },
                "uf": {
                    "type": "string"
                }
            }
        },
        "types.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "types.MetadadosInfo": {
            "type": "object",
            "properties": {
                "duracao": {
                    "type": "string"
                },
                "fonte": {
                    "description": "\"cache\" ou \"online\"",
                    "type": "string"
                },
                "sucesso": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                },
                "url_consulta": {
                    "type": "string"
                }
            }
        },
        "types.NaturezaJuridica": {
            "type": "object",
            "properties": {
                "codigo": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                }
            }
        },
        "types.QueueInfo": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "pending": {
                    "type": "integer"
                },
                "processing": {
                    "type": "integer"
                }
            }
        },
        "types.SituacaoInfo": {
            "type": "object",
            "properties": {
                "cadastral": {
                    "type": "string"
                },
                "data_situacao": {
                    "type": "string"
                },
                "data_situacao_especial": {
                    "type": "string"
                },
                "motivo": {
                    "type": "string"
                },
                "situacao_especial": {
                    "type": "string"
                }
            }
        },
        "types.SystemInfo": {
            "type": "object",
            "properties": {
                "go_version": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "types.WorkerInfo": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                },
                "idle": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.WorkerStats": {
            "type": "object",
            "properties": {
                "cache": {
                    "$ref": "#/definitions/types.CacheInfo"
                },
                "queue": {
                    "$ref": "#/definitions/types.QueueInfo"
                },
                "system": {
                    "$ref": "#/definitions/types.SystemInfo"
                },
                "workers": {
                    "$ref": "#/definitions/types.WorkerInfo"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "CNPJ Consultor API",
	Description:      "API para consulta automatizada de CNPJs na Receita Federal com resolução automática de captcha",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
