basePath: /
definitions:
  models.BatchSintegraRequest:
    description: Estrutura de dados para requisição de consulta em lote de CNPJs
    properties:
      cnpjs:
        description: |-
          Lista de CNPJs para consulta (cada CNPJ deve ter 14 dígitos numéricos)
          @example ["38139407000177","27394162000170"]
        example:
        - '["38139407000177"'
        - '"27394162000170"]'
        items:
          type: string
        maxItems: 10
        minItems: 1
        type: array
    required:
    - cnpjs
    type: object
  models.BatchSintegraResponse:
    description: Dados estruturados retornados pela consulta em lote no Sintegra MA
    properties:
      error_count:
        description: |-
          Número de consultas com erro
          @example 1
        example: 1
        type: integer
      errors:
        additionalProperties:
          type: string
        description: |-
          Erros das consultas que falharam
          Mapa onde a chave é o CNPJ e o valor é a mensagem de erro
        type: object
      execution_time:
        description: |-
          Tempo total de execução do lote (formato: "45s" ou "2m30s")
          @example "1m15s"
        example: 1m15s
        type: string
      invalid_cnpjs:
        description: |-
          Lista de CNPJs inválidos que não foram processados
          @example ["123456"]
        example:
        - '["123456"]'
        items:
          type: string
        type: array
      results:
        additionalProperties:
          $ref: '#/definitions/models.SintegraResponse'
        description: |-
          Resultados das consultas bem-sucedidas
          Mapa onde a chave é o CNPJ e o valor é o resultado da consulta
        type: object
      success_count:
        description: |-
          Número de consultas bem-sucedidas
          @example 2
        example: 2
        type: integer
      timestamp:
        description: |-
          Timestamp da consulta
          @example "2025-08-25T17:25:30.468715-03:00"
        example: "2025-08-25T17:25:30.468715-03:00"
        type: string
      total:
        description: |-
          Número total de CNPJs processados
          @example 3
        example: 3
        type: integer
    type: object
  models.CNAEData:
    properties:
      codigo:
        type: string
      descricao:
        type: string
    type: object
  models.EnderecoData:
    properties:
      bairro:
        type: string
      cep:
        type: string
      complemento:
        type: string
      ddd:
        type: string
      logradouro:
        type: string
      municipio:
        type: string
      numero:
        type: string
      telefone:
        type: string
      uf:
        type: string
    type: object
  models.ErrorDetails:
    properties:
      code:
        description: |-
          Código do erro
          @example "INVALID_CNPJ"
        example: INVALID_CNPJ
        type: string
      details:
        description: Detalhes adicionais do erro
      message:
        description: |-
          Mensagem do erro
          @example "CNPJ inválido. Deve conter 14 dígitos"
        example: CNPJ inválido. Deve conter 14 dígitos
        type: string
    type: object
  models.HealthResponse:
    properties:
      service:
        type: string
      status:
        type: string
      uptime:
        type: string
      version:
        type: string
    type: object
  models.ObrigacoesData:
    properties:
      cte_a_partir_de:
        type: string
      edf_a_partir_de:
        type: string
      nfe_a_partir_de:
        type: string
    type: object
  models.ResponseMeta:
    properties:
      execution_time:
        description: |-
          Tempo de execução da operação
          @example "1.234s"
        example: 1.234s
        type: string
      request_id:
        description: |-
          ID da requisição para rastreamento
          @example "req_123456789"
        example: req_123456789
        type: string
      timestamp:
        description: |-
          Timestamp da resposta em formato ISO 8601
          @example "2025-08-25T17:25:30.468715-03:00"
        example: "2025-08-25T17:25:30.468715-03:00"
        type: string
      version:
        description: |-
          Versão da API
          @example "v1"
        example: v1
        type: string
    type: object
  models.SintegraData:
    properties:
      cgc:
        type: string
      cnae_principal:
        type: string
      cnae_secundarios:
        items:
          $ref: '#/definitions/models.CNAEData'
        type: array
      data_consulta:
        type: string
      data_situacao_cadastral:
        type: string
      endereco:
        $ref: '#/definitions/models.EnderecoData'
      inscricao_estadual:
        type: string
      numero_consulta:
        type: string
      obrigacoes:
        $ref: '#/definitions/models.ObrigacoesData'
      observacao:
        type: string
      razao_social:
        type: string
      regime_apuracao:
        type: string
      situacao_cadastral:
        type: string
    type: object
  models.SintegraRequest:
    description: Estrutura de dados para requisição de consulta CNPJ
    properties:
      cnpj:
        description: |-
          CNPJ da empresa para consulta (apenas números, 14 dígitos)
          @example "38139407000177"
        example: "38139407000177"
        type: string
    required:
    - cnpj
    type: object
  models.SintegraResponse:
    description: Dados estruturados retornados pela consulta no Sintegra MA
    properties:
      captcha_solved:
        description: |-
          Indica se o CAPTCHA foi resolvido automaticamente
          @example true
        example: true
        type: boolean
      cnpj:
        description: |-
          CNPJ consultado
          @example "38139407000177"
        example: "38139407000177"
        type: string
      data:
        allOf:
        - $ref: '#/definitions/models.SintegraData'
        description: Dados estruturados da empresa
      execution_time:
        description: |-
          Tempo de execução da consulta (formato: "45s" ou "2m30s")
          @example "45s"
        example: 45s
        type: string
      status:
        description: |-
          Status da consulta (sucesso, erro_captcha, erro_extracao)
          @example "sucesso"
        example: sucesso
        type: string
      timestamp:
        description: |-
          Timestamp da consulta
          @example "2025-08-25T17:25:30.468715-03:00"
        example: "2025-08-25T17:25:30.468715-03:00"
        type: string
      url:
        description: |-
          URL da página de resultado no Sintegra
          @example "https://sistemas1.sefaz.ma.gov.br/sintegra/..."
        example: https://sistemas1.sefaz.ma.gov.br/sintegra/...
        type: string
    type: object
  models.StandardResponse:
    description: Estrutura padrão unificada de resposta para todos os endpoints
    properties:
      data:
        description: Dados retornados pela operação (apenas quando status = success)
      error:
        allOf:
        - $ref: '#/definitions/models.ErrorDetails'
        description: Detalhes do erro (apenas quando status = error)
      message:
        description: |-
          Mensagem descritiva da operação
          @example "Consulta realizada com sucesso"
        example: Consulta realizada com sucesso
        type: string
      meta:
        allOf:
        - $ref: '#/definitions/models.ResponseMeta'
        description: Metadados da resposta
      status:
        description: |-
          Status da operação (success, error, warning, info)
          @example "success"
        example: success
        type: string
    type: object
  models.StatusRequest:
    properties:
      cnpj:
        description: CNPJ da empresa para verificar status
        type: string
    required:
    - cnpj
    type: object
  models.StatusResponse:
    properties:
      cnpj:
        description: CNPJ consultado
        type: string
      mensagem:
        description: Mensagem adicional sobre o status
        type: string
      status:
        description: Status da consulta (em_andamento, concluida, erro, nao_encontrada)
        type: string
      tempo_estimado:
        description: Tempo estimado para conclusão (em segundos), apenas quando status=em_andamento
        type: integer
      timestamp:
        description: Timestamp da verificação
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: contato@nexconsult.com
    name: NexConsult
    url: https://nexconsult.com
  description: API REST para consulta automatizada no Sintegra do Maranhão com resolução
    automática de reCAPTCHA v2 e extração estruturada de dados.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: NexConsult Sintegra MA API
  version: 1.0.0
paths:
  /:
    get:
      description: Exibe informações básicas sobre a API, endpoints disponíveis e
        exemplos de uso
      produces:
      - application/json
      responses:
        "200":
          description: Informações da API
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: API Information
      tags:
      - System
  /api/v1/sintegra/consultar:
    post:
      consumes:
      - application/json
      description: Executa consulta automatizada no Sintegra MA com resolução de CAPTCHA
        e extração de dados estruturados
      parameters:
      - description: Dados do CNPJ para consulta
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SintegraRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Consulta realizada com sucesso
          schema:
            allOf:
            - $ref: '#/definitions/models.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.SintegraResponse'
              type: object
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/models.StandardResponse'
        "429":
          description: Rate limit excedido
          schema:
            $ref: '#/definitions/models.StandardResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: Consultar CNPJ no Sintegra MA
      tags:
      - Sintegra
  /api/v1/sintegra/consultar-lote:
    post:
      consumes:
      - application/json
      description: Executa consulta automatizada em lote no Sintegra MA para múltiplos
        CNPJs simultaneamente
      parameters:
      - description: Lista de CNPJs para consulta em lote (máximo 10)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BatchSintegraRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Consulta em lote realizada com sucesso
          schema:
            allOf:
            - $ref: '#/definitions/models.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.BatchSintegraResponse'
              type: object
        "400":
          description: Requisição inválida ou CNPJs inválidos
          schema:
            $ref: '#/definitions/models.StandardResponse'
        "429":
          description: Rate limit excedido
          schema:
            $ref: '#/definitions/models.StandardResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: Consultar múltiplos CNPJs em lote
      tags:
      - Sintegra
  /api/v1/sintegra/status:
    post:
      consumes:
      - application/json
      description: Verifica se uma consulta de CNPJ está em andamento ou concluída
      parameters:
      - description: CNPJ para verificar status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.StatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Status da consulta
          schema:
            allOf:
            - $ref: '#/definitions/models.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.StatusResponse'
              type: object
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/models.StandardResponse'
        "500":
          description: Erro interno do servidor
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: Verifica o status de uma consulta de CNPJ
      tags:
      - Sintegra
  /docs:
    get:
      description: Documentação detalhada dos endpoints disponíveis, formatos de resposta
        e exemplos
      produces:
      - application/json
      responses:
        "200":
          description: Documentação completa da API
          schema:
            $ref: '#/definitions/models.StandardResponse'
      summary: API Documentation
      tags:
      - System
  /health:
    get:
      description: Verifica o status de saúde da API, tempo de atividade e versão
      produces:
      - application/json
      responses:
        "200":
          description: API funcionando corretamente
          schema:
            allOf:
            - $ref: '#/definitions/models.StandardResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.HealthResponse'
              type: object
      summary: Health Check
      tags:
      - System
schemes:
- http
- https
swagger: "2.0"
